### ISSUE TITLE
How can I select the same keyframes as used in your TCVOM paper?

### ISSUE THREAD

**Issue by Hongje** [yunkezhang/TCVOM-TGM#1]
Thank you for the dataset and source code!
I want to conduct a fair comparison with your TCVOM paper.
In this paper, several user-annotated (GT) trimaps at keyframes are used to generate trimaps.
I wonder which frames are selected as keyframes in your TCVOM paper for testing on VideoMatting108 validation set (Table 1) and videomatting.com (Table 2).

**Comment by yunkezhang** [comment]
Thank you for your interest in our work!
Results in Table 1 and Table 2 use the original per-frame trimaps.
Trimaps in our VM108 dataset are generated on the fly by dilating the UR. The details are in TCVOM's code.
Trimaps in the videomatting.com benchmark is provided by the dataset.

**Comment by Hongje** [comment]
I got it.
I really thank you for your reply!
